-- Optional portfolio deployment. Select an authorized existing warehouse before running.
-- Example: USE WAREHOUSE MY_EXISTING_XS_WAREHOUSE;

CREATE DATABASE IF NOT EXISTS F1_STEWARDS_PORTFOLIO;
USE DATABASE F1_STEWARDS_PORTFOLIO;

CREATE SCHEMA IF NOT EXISTS METADATA;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS AUDIT;
CREATE SCHEMA IF NOT EXISTS ANALYSIS;
CREATE SCHEMA IF NOT EXISTS LANDING;

CREATE FILE FORMAT IF NOT EXISTS LANDING.PARQUET_SNAPPY
    TYPE = PARQUET
    USE_LOGICAL_TYPE = TRUE;

CREATE STAGE IF NOT EXISTS LANDING.F1_STEWARDS_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY');

LIST @LANDING.F1_STEWARDS_STAGE;
