USE DATABASE F1_STEWARDS_PORTFOLIO;

-- Snowflake standard-table constraints are metadata controls; quality SQL enforces cross-schema
-- integrity explicitly so the same release rules remain visible in DuckDB and Snowflake.

CREATE TABLE IF NOT EXISTS METADATA.EVENTS (
    EVENT_ID VARCHAR PRIMARY KEY,
    SEASON NUMBER(4, 0) NOT NULL,
    ROUND_NUMBER NUMBER(3, 0),
    EVENT_NAME VARCHAR NOT NULL,
    COUNTRY VARCHAR,
    EVENT_DATE DATE,
    ARCHIVE_URL VARCHAR NOT NULL,
    GUIDELINE_REGIME VARCHAR NOT NULL,
    IS_PILOT BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW.SOURCE_DOCUMENTS (
    DOCUMENT_ID VARCHAR PRIMARY KEY,
    EVENT_ID VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    DOCUMENT_URL VARCHAR NOT NULL,
    ARCHIVE_URL VARCHAR NOT NULL,
    DOCUMENT_CLASS VARCHAR NOT NULL,
    PUBLISHED_AT_RAW VARCHAR,
    PUBLISHED_AT TIMESTAMP_TZ,
    DISCOVERED_AT TIMESTAMP_TZ NOT NULL,
    RETRIEVED_AT TIMESTAMP_TZ,
    SOURCE_DOMAIN VARCHAR NOT NULL,
    CONTENT_SHA256 VARCHAR(64),
    HTTP_STATUS NUMBER(3, 0),
    CONTENT_TYPE VARCHAR,
    RETRIEVAL_ERROR VARCHAR,
    IS_RECALLED BOOLEAN NOT NULL,
    SUPERSEDES_DOCUMENT_ID VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.DOCUMENT_TEXT (
    DOCUMENT_ID VARCHAR PRIMARY KEY,
    PARSER_VERSION VARCHAR NOT NULL,
    PARSED_AT TIMESTAMP_TZ NOT NULL,
    PAGE_COUNT NUMBER(6, 0) NOT NULL,
    RAW_TEXT VARCHAR NOT NULL,
    FACT_TEXT VARCHAR,
    INFRINGEMENT_TEXT VARCHAR,
    DECISION_TEXT VARCHAR,
    REASON_TEXT VARCHAR,
    PARSER_WARNINGS_JSON VARCHAR,
    DRIVER_NUMBER NUMBER(3, 0),
    DRIVER_NAME VARCHAR,
    SESSION_TYPE VARCHAR,
    INCIDENT_TIME_RAW VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.FASTF1_RESULTS (
    EVENT_ID VARCHAR NOT NULL,
    DRIVER_NUMBER NUMBER(3, 0) NOT NULL,
    DRIVER_NAME VARCHAR,
    ABBREVIATION VARCHAR,
    COUNTRY_CODE VARCHAR,
    TEAM_NAME VARCHAR,
    GRID_POSITION FLOAT,
    FINISH_POSITION FLOAT,
    CLASSIFIED_POSITION VARCHAR,
    STATUS VARCHAR,
    POINTS FLOAT,
    RETRIEVED_AT TIMESTAMP_TZ NOT NULL,
    RESULT_TIME_SECONDS FLOAT,
    LAPS_COMPLETED FLOAT,
    CLASSIFICATION_GAP_SECONDS FLOAT,
    PRIMARY KEY (EVENT_ID, DRIVER_NUMBER)
);

CREATE TABLE IF NOT EXISTS METADATA.REGULATORY_SOURCES (
    SOURCE_ID VARCHAR PRIMARY KEY,
    DOCUMENT_TYPE VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    ISSUING_BODY VARCHAR NOT NULL,
    PUBLICATION_DATE DATE,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_THROUGH DATE,
    SOURCE_URL VARCHAR NOT NULL,
    RESOLVED_URL VARCHAR,
    SOURCE_STATUS VARCHAR NOT NULL,
    APPLICABILITY_STATUS VARCHAR NOT NULL,
    IS_GUIDELINE BOOLEAN NOT NULL,
    NOTES VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS METADATA.EVENT_REGULATORY_SOURCES (
    EVENT_ID VARCHAR NOT NULL,
    SOURCE_ID VARCHAR NOT NULL,
    EVENT_ROLE VARCHAR NOT NULL,
    PRIMARY KEY (EVENT_ID, SOURCE_ID)
);

CREATE TABLE IF NOT EXISTS METADATA.SPORTING_REGULATION_ISSUES (
    SOURCE_ID VARCHAR PRIMARY KEY,
    SEASON NUMBER(4, 0) NOT NULL,
    PRECEDENCE NUMBER(4, 0) NOT NULL,
    PUBLICATION_DATE DATE NOT NULL,
    ISSUE_LABEL VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    ARCHIVE_URL VARCHAR NOT NULL,
    DOCUMENT_URL VARCHAR,
    RESOLUTION_STATUS VARCHAR NOT NULL,
    SELECTION_STATUS VARCHAR NOT NULL,
    NOTES VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS METADATA.INTERNATIONAL_SPORTING_CODE_ISSUES (
    SOURCE_ID VARCHAR PRIMARY KEY,
    SEASON NUMBER(4, 0) NOT NULL,
    PRECEDENCE NUMBER(4, 0) NOT NULL,
    PUBLICATION_DATE DATE,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_THROUGH DATE NOT NULL,
    TITLE VARCHAR NOT NULL,
    ARCHIVE_URL VARCHAR NOT NULL,
    DOCUMENT_URL VARCHAR,
    RESOLUTION_STATUS VARCHAR NOT NULL,
    SELECTION_STATUS VARCHAR NOT NULL,
    NOTES VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS METADATA.CLAIM_LEDGER (
    CLAIM_ID VARCHAR PRIMARY KEY,
    REPORT_SECTION VARCHAR NOT NULL,
    RESEARCH_QUESTION VARCHAR NOT NULL,
    CLAIM_TEMPLATE VARCHAR NOT NULL,
    ESTIMAND VARCHAR NOT NULL,
    POPULATION VARCHAR NOT NULL,
    REQUIRED_METHOD VARCHAR NOT NULL,
    MINIMUM_ACCEPTANCE VARCHAR NOT NULL,
    REQUIRED_SENSITIVITY VARCHAR NOT NULL,
    EVIDENCE_GRADE_IF_MET VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    PRIMARY_LIMITATION VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CURATED.ADJUDICATIONS (
    ADJUDICATION_ID VARCHAR PRIMARY KEY,
    INCIDENT_ID VARCHAR NOT NULL,
    EVENT_ID VARCHAR NOT NULL,
    SOURCE_DOCUMENT_ID VARCHAR NOT NULL,
    SOURCE_URL VARCHAR NOT NULL,
    ACCUSED_DRIVER_NUMBER NUMBER(3, 0) NOT NULL,
    AFFECTED_DRIVER_NUMBER NUMBER(3, 0) NOT NULL,
    SESSION_TYPE VARCHAR NOT NULL,
    LAP_NUMBER NUMBER(4, 0) NOT NULL,
    TURN_NUMBER NUMBER(4, 0),
    INCIDENT_FAMILY VARCHAR NOT NULL,
    OUTCOME_FAMILY VARCHAR NOT NULL,
    PENALTY_SECONDS FLOAT,
    PENALTY_POINTS NUMBER(3, 0),
    GRID_PLACES NUMBER(3, 0),
    FAULT_LANGUAGE VARCHAR NOT NULL,
    EVIDENCE_VIDEO BOOLEAN NOT NULL,
    EVIDENCE_POSITIONING BOOLEAN NOT NULL,
    EVIDENCE_TELEMETRY BOOLEAN NOT NULL,
    EVIDENCE_TEAM_RADIO BOOLEAN NOT NULL,
    GUIDELINE_REGIME VARCHAR NOT NULL,
    GUIDELINE_CLAUSE VARCHAR NOT NULL,
    GUIDELINE_EXPECTED_OUTCOME VARCHAR NOT NULL,
    CONFORMANCE_STATUS VARCHAR NOT NULL,
    MITIGATING_FACTOR_WRITTEN BOOLEAN NOT NULL,
    FIRST_LAP BOOLEAN NOT NULL,
    INCLUDE_PRIMARY BOOLEAN NOT NULL,
    CODER_ID VARCHAR NOT NULL,
    REVIEW_STATUS VARCHAR NOT NULL,
    CODING_NOTES VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CURATED.IMPACT_ASSESSMENTS (
    IMPACT_ASSESSMENT_ID VARCHAR PRIMARY KEY,
    ADJUDICATION_ID VARCHAR NOT NULL,
    EVENT_ID VARCHAR NOT NULL,
    SOURCE_DOCUMENT_ID VARCHAR NOT NULL,
    CLASSIFICATION_SOURCE_DOCUMENT_ID VARCHAR NOT NULL,
    DRIVER_NUMBER NUMBER(3, 0) NOT NULL,
    SANCTION_TYPE VARCHAR NOT NULL,
    PENALTY_SECONDS FLOAT,
    GRID_PLACES NUMBER(3, 0),
    SANCTION_APPLICATION VARCHAR NOT NULL,
    IMPACT_LEVEL VARCHAR NOT NULL,
    OFFICIAL_FINISH_POSITION NUMBER(3, 0),
    COUNTERFACTUAL_FINISH_POSITION NUMBER(3, 0),
    POSITIONS_GAINED_WITHOUT_PENALTY NUMBER(3, 0),
    OFFICIAL_POINTS FLOAT NOT NULL,
    COUNTERFACTUAL_POINTS FLOAT,
    POINTS_GAINED_WITHOUT_PENALTY FLOAT,
    PODIUM_CHANGED BOOLEAN,
    WIN_CHANGED BOOLEAN,
    CALCULATION_METHOD VARCHAR NOT NULL,
    ASSUMPTIONS VARCHAR NOT NULL,
    REVIEW_STATUS VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CURATED.HARM_ASSESSMENTS (
    HARM_ASSESSMENT_ID VARCHAR PRIMARY KEY,
    ADJUDICATION_ID VARCHAR NOT NULL,
    INCIDENT_ID VARCHAR NOT NULL,
    EVENT_ID VARCHAR NOT NULL,
    SOURCE_DOCUMENT_ID VARCHAR NOT NULL,
    CLASSIFICATION_SOURCE_DOCUMENT_ID VARCHAR NOT NULL,
    AFFECTED_DRIVER_NUMBER NUMBER(3, 0) NOT NULL,
    COUNTERPARTY_DRIVER_NUMBER NUMBER(3, 0) NOT NULL,
    RESPONSIBILITY_STATUS VARCHAR NOT NULL,
    HARM_EVIDENCE_LEVEL VARCHAR NOT NULL,
    DAMAGE_EVIDENCE VARCHAR NOT NULL,
    DAMAGE_TYPE VARCHAR NOT NULL,
    REPAIR_STOP_REQUIRED VARCHAR NOT NULL,
    PIT_LAP NUMBER(4, 0),
    PIT_RESPONSE_STATUS VARCHAR NOT NULL,
    PIT_LANE_LOSS_SECONDS FLOAT,
    REPAIR_STATIONARY_SECONDS FLOAT,
    RETIREMENT_STATUS VARCHAR NOT NULL,
    POSITION_BEFORE NUMBER(3, 0),
    POSITION_AFTER NUMBER(3, 0),
    NET_POSITIONS_LOST_OBSERVED NUMBER(3, 0),
    AFFECTED_RELATIVE_TIME_LOSS_SECONDS FLOAT,
    POST_INCIDENT_CLEAN_LAPS NUMBER(4, 0) NOT NULL,
    PERSISTENT_PACE_STATUS VARCHAR NOT NULL,
    PERSISTENT_DELTA_PER_LAP_SECONDS FLOAT,
    PERSISTENT_LAPS_EXPOSED NUMBER(4, 0),
    PERSISTENT_LOSS_SECONDS_LOWER FLOAT,
    PERSISTENT_LOSS_SECONDS_ESTIMATE FLOAT,
    PERSISTENT_LOSS_SECONDS_UPPER FLOAT,
    NET_EFFECT_DIRECTION VARCHAR NOT NULL,
    BENEFIT_MECHANISM VARCHAR,
    EVIDENCE_URLS VARCHAR NOT NULL,
    CALCULATION_METHOD VARCHAR NOT NULL,
    ASSUMPTIONS VARCHAR NOT NULL,
    REVIEW_STATUS VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIT.INDEPENDENT_REVIEW (
    REVIEW_ID VARCHAR PRIMARY KEY,
    TARGET_TYPE VARCHAR NOT NULL,
    TARGET_ID VARCHAR NOT NULL,
    EVIDENCE_URLS VARCHAR NOT NULL,
    INITIAL_SUMMARY VARCHAR NOT NULL,
    REVIEW_STATUS VARCHAR NOT NULL,
    REVIEWER_ID VARCHAR,
    REVIEWED_AT_UTC TIMESTAMP_TZ,
    REVIEW_MINUTES FLOAT,
    CORRECTED_FIELDS_JSON VARCHAR,
    REVIEWER_NOTES VARCHAR
);
