USE DATABASE F1_STEWARDS_PORTFOLIO;

-- Upload the 12 manifest-listed Parquet files to LANDING.F1_STEWARDS_STAGE first.
-- COPY load metadata prevents an unchanged staged file from loading twice unless FORCE is enabled.

COPY INTO METADATA.EVENTS
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('metadata_events.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.SOURCE_DOCUMENTS
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('raw_source_documents.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.DOCUMENT_TEXT
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('raw_document_text.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.FASTF1_RESULTS
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('raw_fastf1_results.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO METADATA.REGULATORY_SOURCES
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('metadata_regulatory_sources.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO METADATA.EVENT_REGULATORY_SOURCES
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('metadata_event_regulatory_sources.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO METADATA.SPORTING_REGULATION_ISSUES
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('metadata_sporting_regulation_issues.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO METADATA.INTERNATIONAL_SPORTING_CODE_ISSUES
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('metadata_international_sporting_code_issues.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO METADATA.CLAIM_LEDGER
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('metadata_claim_ledger.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CURATED.ADJUDICATIONS
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('curated_adjudications.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CURATED.IMPACT_ASSESSMENTS
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('curated_impact_assessments.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO AUDIT.INDEPENDENT_REVIEW
FROM @LANDING.F1_STEWARDS_STAGE
FILES = ('audit_independent_review.parquet')
FILE_FORMAT = (FORMAT_NAME = 'F1_STEWARDS_PORTFOLIO.LANDING.PARQUET_SNAPPY')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';
