USE DATABASE F1_STEWARDS_PORTFOLIO;

CREATE OR REPLACE VIEW ANALYSIS.V_EVIDENCE_LINKED_ADJUDICATIONS AS
SELECT
    a.*,
    e.SEASON,
    e.EVENT_DATE,
    e.EVENT_NAME,
    d.DOCUMENT_URL AS OFFICIAL_DECISION_URL,
    t.FACT_TEXT,
    t.DECISION_TEXT,
    t.REASON_TEXT
FROM CURATED.ADJUDICATIONS AS a
JOIN METADATA.EVENTS AS e
  ON a.EVENT_ID = e.EVENT_ID
JOIN RAW.SOURCE_DOCUMENTS AS d
  ON a.SOURCE_DOCUMENT_ID = d.DOCUMENT_ID
LEFT JOIN RAW.DOCUMENT_TEXT AS t
  ON a.SOURCE_DOCUMENT_ID = t.DOCUMENT_ID;

CREATE OR REPLACE VIEW ANALYSIS.V_REVIEW_STATUS AS
SELECT
    'adjudication' AS TARGET_TYPE,
    a.ADJUDICATION_ID AS TARGET_ID,
    a.REVIEW_STATUS AS CURATED_REVIEW_STATUS,
    r.REVIEW_STATUS AS INDEPENDENT_REVIEW_STATUS,
    r.REVIEWER_ID,
    r.REVIEWED_AT_UTC,
    r.REVIEW_MINUTES
FROM CURATED.ADJUDICATIONS AS a
LEFT JOIN AUDIT.INDEPENDENT_REVIEW AS r
  ON r.TARGET_TYPE = 'adjudication'
 AND r.TARGET_ID = a.ADJUDICATION_ID
UNION ALL
SELECT
    'impact_assessment' AS TARGET_TYPE,
    i.IMPACT_ASSESSMENT_ID AS TARGET_ID,
    i.REVIEW_STATUS AS CURATED_REVIEW_STATUS,
    r.REVIEW_STATUS AS INDEPENDENT_REVIEW_STATUS,
    r.REVIEWER_ID,
    r.REVIEWED_AT_UTC,
    r.REVIEW_MINUTES
FROM CURATED.IMPACT_ASSESSMENTS AS i
LEFT JOIN AUDIT.INDEPENDENT_REVIEW AS r
  ON r.TARGET_TYPE = 'impact_assessment'
 AND r.TARGET_ID = i.IMPACT_ASSESSMENT_ID;

CREATE OR REPLACE VIEW ANALYSIS.V_EVENT_SPORTING_REGULATION_SELECTION AS
SELECT
    e.EVENT_ID,
    e.SEASON,
    e.EVENT_NAME,
    e.EVENT_DATE,
    r.SOURCE_ID,
    r.PRECEDENCE,
    r.PUBLICATION_DATE,
    r.ISSUE_LABEL,
    r.DOCUMENT_URL,
    r.RESOLUTION_STATUS,
    r.SELECTION_STATUS,
    DATEDIFF('day', r.PUBLICATION_DATE, e.EVENT_DATE) AS DAYS_BEFORE_EVENT
FROM METADATA.EVENTS AS e
JOIN METADATA.SPORTING_REGULATION_ISSUES AS r
  ON e.SEASON = r.SEASON
 AND r.PUBLICATION_DATE <= e.EVENT_DATE
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY e.EVENT_ID
    ORDER BY r.PUBLICATION_DATE DESC, r.PRECEDENCE DESC
) = 1;

CREATE OR REPLACE VIEW ANALYSIS.V_EVENT_INTERNATIONAL_CODE_SELECTION AS
SELECT
    e.EVENT_ID,
    e.SEASON,
    e.EVENT_NAME,
    e.EVENT_DATE,
    c.SOURCE_ID,
    c.PRECEDENCE,
    c.PUBLICATION_DATE,
    c.EFFECTIVE_FROM,
    c.EFFECTIVE_THROUGH,
    c.DOCUMENT_URL,
    c.RESOLUTION_STATUS,
    c.SELECTION_STATUS
FROM METADATA.EVENTS AS e
JOIN METADATA.INTERNATIONAL_SPORTING_CODE_ISSUES AS c
  ON e.SEASON = c.SEASON
 AND e.EVENT_DATE BETWEEN c.EFFECTIVE_FROM AND c.EFFECTIVE_THROUGH
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY e.EVENT_ID
    ORDER BY c.EFFECTIVE_FROM DESC, c.PRECEDENCE DESC
) = 1;

-- Portfolio summary. Keep candidate coding and unresolved review visible beside record counts.
SELECT
    (SELECT COUNT(*) FROM METADATA.EVENTS) AS PILOT_EVENTS,
    (SELECT COUNT(*) FROM RAW.SOURCE_DOCUMENTS) AS SOURCE_RECORDS,
    (SELECT COUNT(*) FROM CURATED.ADJUDICATIONS) AS CANDIDATE_ADJUDICATIONS,
    (SELECT COUNT(DISTINCT INCIDENT_ID) FROM CURATED.ADJUDICATIONS) AS INCIDENTS,
    (SELECT COUNT(*) FROM CURATED.IMPACT_ASSESSMENTS) AS IMPACT_ASSESSMENTS,
    (SELECT COUNT_IF(REVIEW_STATUS IN ('pending', 'needs_discussion'))
       FROM AUDIT.INDEPENDENT_REVIEW) AS UNRESOLVED_REVIEW_TARGETS;

-- Outcome distribution with an explicit denominator; descriptive only while provisional.
SELECT
    SEASON,
    OUTCOME_FAMILY,
    COUNT(*) AS ADJUDICATIONS,
    SUM(COUNT(*)) OVER (PARTITION BY SEASON) AS SEASON_ADJUDICATIONS,
    COUNT(*) / NULLIF(SUM(COUNT(*)) OVER (PARTITION BY SEASON), 0) AS SHARE_OF_SEASON
FROM ANALYSIS.V_EVIDENCE_LINKED_ADJUDICATIONS
GROUP BY SEASON, OUTCOME_FAMILY
ORDER BY SEASON, ADJUDICATIONS DESC, OUTCOME_FAMILY;

-- Public-guideline conformance is only interpreted for 2025 and remains candidate coding.
SELECT
    CONFORMANCE_STATUS,
    COUNT(*) AS ADJUDICATIONS,
    COUNT_IF(OUTCOME_FAMILY = 'no_further_action') AS NO_FURTHER_ACTION,
    COUNT_IF(OUTCOME_FAMILY <> 'no_further_action') AS SANCTIONED
FROM ANALYSIS.V_EVIDENCE_LINKED_ADJUDICATIONS
WHERE SEASON = 2025
GROUP BY CONFORMANCE_STATUS
ORDER BY ADJUDICATIONS DESC, CONFORMANCE_STATUS;

-- Exact mechanical arithmetic is not aggregated with non-estimable counterfactuals.
SELECT
    IMPACT_LEVEL,
    COUNT(*) AS ASSESSMENTS,
    SUM(IFF(IMPACT_LEVEL = 'mechanical', POSITIONS_GAINED_WITHOUT_PENALTY, NULL))
        AS MECHANICAL_POSITIONS_CHANGED,
    SUM(IFF(IMPACT_LEVEL = 'mechanical', POINTS_GAINED_WITHOUT_PENALTY, NULL))
        AS MECHANICAL_POINTS_CHANGED
FROM CURATED.IMPACT_ASSESSMENTS
GROUP BY IMPACT_LEVEL
ORDER BY IMPACT_LEVEL;

-- Claim status is a governance output, not hidden report prose.
SELECT
    REPORT_SECTION,
    STATUS,
    EVIDENCE_GRADE_IF_MET,
    COUNT(*) AS CLAIMS
FROM METADATA.CLAIM_LEDGER
GROUP BY REPORT_SECTION, STATUS, EVIDENCE_GRADE_IF_MET
ORDER BY REPORT_SECTION, STATUS;
