USE DATABASE F1_STEWARDS_PORTFOLIO;

-- Frozen three-event pilot counts from the local manifest. Every status must be PASS.
WITH OBSERVED AS (
    SELECT 'METADATA.EVENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM METADATA.EVENTS
    UNION ALL
    SELECT 'RAW.SOURCE_DOCUMENTS', COUNT(*) FROM RAW.SOURCE_DOCUMENTS
    UNION ALL
    SELECT 'RAW.DOCUMENT_TEXT', COUNT(*) FROM RAW.DOCUMENT_TEXT
    UNION ALL
    SELECT 'RAW.FASTF1_RESULTS', COUNT(*) FROM RAW.FASTF1_RESULTS
    UNION ALL
    SELECT 'METADATA.REGULATORY_SOURCES', COUNT(*) FROM METADATA.REGULATORY_SOURCES
    UNION ALL
    SELECT 'METADATA.EVENT_REGULATORY_SOURCES', COUNT(*)
    FROM METADATA.EVENT_REGULATORY_SOURCES
    UNION ALL
    SELECT 'METADATA.SPORTING_REGULATION_ISSUES', COUNT(*)
    FROM METADATA.SPORTING_REGULATION_ISSUES
    UNION ALL
    SELECT 'METADATA.INTERNATIONAL_SPORTING_CODE_ISSUES', COUNT(*)
    FROM METADATA.INTERNATIONAL_SPORTING_CODE_ISSUES
    UNION ALL
    SELECT 'METADATA.CLAIM_LEDGER', COUNT(*) FROM METADATA.CLAIM_LEDGER
    UNION ALL
    SELECT 'CURATED.ADJUDICATIONS', COUNT(*) FROM CURATED.ADJUDICATIONS
    UNION ALL
    SELECT 'CURATED.IMPACT_ASSESSMENTS', COUNT(*) FROM CURATED.IMPACT_ASSESSMENTS
    UNION ALL
    SELECT 'CURATED.HARM_ASSESSMENTS', COUNT(*) FROM CURATED.HARM_ASSESSMENTS
    UNION ALL
    SELECT 'CURATED.INCIDENT_LOCATIONS', COUNT(*) FROM CURATED.INCIDENT_LOCATIONS
    UNION ALL
    SELECT 'CURATED.INCIDENT_RELATIONS', COUNT(*) FROM CURATED.INCIDENT_RELATIONS
    UNION ALL
    SELECT 'CURATED.CROSS_EVENT_SANCTION_EFFECTS', COUNT(*)
    FROM CURATED.CROSS_EVENT_SANCTION_EFFECTS
    UNION ALL
    SELECT 'AUDIT.INDEPENDENT_REVIEW', COUNT(*) FROM AUDIT.INDEPENDENT_REVIEW
),
EXPECTED AS (
    SELECT COLUMN1 AS TABLE_NAME, COLUMN2 AS EXPECTED_ROWS
    FROM VALUES
        ('METADATA.EVENTS', 3),
        ('RAW.SOURCE_DOCUMENTS', 156),
        ('RAW.DOCUMENT_TEXT', 26),
        ('RAW.FASTF1_RESULTS', 60),
        ('METADATA.REGULATORY_SOURCES', 11),
        ('METADATA.EVENT_REGULATORY_SOURCES', 11),
        ('METADATA.SPORTING_REGULATION_ISSUES', 65),
        ('METADATA.INTERNATIONAL_SPORTING_CODE_ISSUES', 9),
        ('METADATA.CLAIM_LEDGER', 14),
        ('CURATED.ADJUDICATIONS', 9),
        ('CURATED.IMPACT_ASSESSMENTS', 4),
        ('CURATED.HARM_ASSESSMENTS', 9),
        ('CURATED.INCIDENT_LOCATIONS', 1),
        ('CURATED.INCIDENT_RELATIONS', 2),
        ('CURATED.CROSS_EVENT_SANCTION_EFFECTS', 1),
        ('AUDIT.INDEPENDENT_REVIEW', 26)
)
SELECT
    e.TABLE_NAME,
    e.EXPECTED_ROWS,
    o.ROW_COUNT AS ACTUAL_ROWS,
    IFF(o.ROW_COUNT = e.EXPECTED_ROWS, 'pass', 'fail') AS STATUS
FROM EXPECTED AS e
LEFT JOIN OBSERVED AS o
  ON e.TABLE_NAME = o.TABLE_NAME
ORDER BY e.TABLE_NAME;

-- Cross-engine semantic parity for the pilot's most important controlled summaries.
SELECT
    COUNT(*) AS ADJUDICATIONS,
    COUNT(DISTINCT INCIDENT_ID) AS INCIDENTS,
    COUNT_IF(OUTCOME_FAMILY = 'no_further_action') AS NO_FURTHER_ACTION,
    COUNT_IF(OUTCOME_FAMILY = 'time_penalty') AS TIME_PENALTIES,
    COUNT_IF(OUTCOME_FAMILY = 'grid_penalty') AS GRID_PENALTIES,
    COUNT_IF(SEASON = 2025) AS ADJUDICATIONS_2025
FROM ANALYSIS.V_EVIDENCE_LINKED_ADJUDICATIONS;

SELECT
    COUNT(*) AS IMPACT_ASSESSMENTS,
    COUNT_IF(IMPACT_LEVEL = 'mechanical') AS MECHANICAL,
    COUNT_IF(IMPACT_LEVEL = 'not_estimable') AS NOT_ESTIMABLE,
    SUM(IFF(IMPACT_LEVEL = 'mechanical', POSITIONS_GAINED_WITHOUT_PENALTY, 0))
        AS MECHANICAL_POSITIONS_CHANGED,
    SUM(IFF(IMPACT_LEVEL = 'mechanical', POINTS_GAINED_WITHOUT_PENALTY, 0))
        AS MECHANICAL_POINTS_CHANGED
FROM CURATED.IMPACT_ASSESSMENTS;

SELECT
    COUNT(*) AS HARM_ASSESSMENTS,
    COUNT_IF(DAMAGE_EVIDENCE IN ('confirmed', 'repair_observed')) AS CONFIRMED_DAMAGE,
    COUNT_IF(REPAIR_STOP_REQUIRED = 'yes') AS REPAIR_STOPS,
    SUM(COALESCE(NET_POSITIONS_LOST_OBSERVED, 0)) AS OBSERVED_NET_POSITIONS_LOST
FROM CURATED.HARM_ASSESSMENTS;
